# Configure main menu and social menu
# [[main]]
# identifier = "home"
# name = "Home"
# url = "/"
# [main.params]
# icon = "home"
# newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/shakir85"

[social.params]
icon = "brand-github"

[[social]]
identifier = "gitlab"
name = "GitLab"
url = "https://gitlab.com/homelabgroup"

[social.params]
icon = "brand-gitlab"

[[social]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/almasaari/"

[social.params]
icon = "brand-linkedin"
